repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # Check poetry state
  - repo: https://github.com/python-poetry/poetry
    rev: "1.5.1"
    hooks:
      - id: poetry-check
        args: ["-C", "./backend"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.8
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: mypy
        additional_dependencies: ["types-aiofiles"]

  - repo: https://github.com/python-poetry/poetry
    rev: "" # add version here
    hooks:
      - id: poetry-check
        args: ["-C", "./backend/core"]
      - id: poetry-lock
        args: ["-C", "./backend/core"]
      - id: poetry-install
        args: ["-C", "./backend/core"]
