[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88
exclude = [".git", "__pycache__", ".mypy_cache", ".pytest_cache"]
select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    # "I",  # isort
    "C", # flake8-comprehensions
    "B", # flake8-bugbear
]
ignore = [
    "B904",
    "B006",
    "E501", # line too long, handled by black
    "B008", # do not perform function calls in argument defaults
    "C901", # too complex
]

[tool.poetry]
name = "backend"
version = "0.1.0"
description = "quivr backend"
authors = ["aminediro <amine@quivr.app>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
langchain = "*"
litellm = "*"
openai = "*"
gitpython = "*"
pdf2image = "*"
nest-asyncio = "*"
pypdf = "*"
supabase = "*"
tiktoken = "*"
fastapi = "*"
python-multipart = "*"
uvicorn = "*"
pypandoc = "*"
docx2txt = "*"
python-jose = "*"
asyncpg = "*"
flake8 = "*"
flake8-black = "*"
pyright = "*"
resend = "*"
html5lib = "*"
beautifulsoup4 = "*"
newspaper3k = "*"
xlrd = "*"
redis = "*"
flower = "*"
boto3 = "*"
botocore = "*"
python-dotenv = "*"
pytest-mock = "*"
pytest-celery = "*"
pytesseract = "*"
async-generator = "*"
posthog = "*"
jq = "*"
pytest = "*"
watchdog = "*"
langchain-community = "*"
langchain-openai = "*"
pydantic-settings = "*"
langfuse = "*"
pandasai = "*"
colorlog = "*"
psycopg2-binary = "*"
celery = { extras = ["redis", "sqs"], version = "*" }
unstructured = { extras = ["all-docs"], version = "*" }
llama-parse = "*"
llama-index = "*"
lxml = { extras = ["html_clean"], version = "*" }
ragas = "*"
datasets = "*"
pytest-dotenv = "*"
fpdf2 = "*"
unidecode = "*"
flashrank = "*"
langchain-cohere = "*"
pyinstrument = "*"
playwright = "*"
langgraph = "*"
tavily-python = "*"
duckduckgo-search = "*"
google-api-python-client = "*"
google-auth-httplib2 = "*"
google-auth-oauthlib = "*"
msal = "*"
sentry-sdk = { version = "^2.5.0", extras = ["fastapi"] }
sqlmodel = "^0.0.19"

[tool.poetry.group.dev.dependencies]
pytest = "*"
mypy = "^1.10.0"
pre-commit = "^3.7.1"
ipykernel = "*"
ruff = "^0.4.8"
