
[tool.poetry]
name = "quivr-monorepo"
version = "0.0.1"
description = "Quivr monorepo"
authors = ["aminediro <amine@quivr.app"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.dev.dependencies]
quivr-core = { path = "core", develop = true }
quivr-api = { path = "api", develop = true }
mypy = "^1.10.0"
pre-commit = "^3.7.1"
ipykernel = "*"
ruff = "^0.4.8"
pytest-asyncio = "^0.23.7"
flake8 = "*"
flake8-black = "*"
pytest = "*"
pytest-dotenv = "*"
pytest-mock = "*"
pytest-celery = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "pytorch-cpu-src"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"
