[project]
name = "chatbot"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Stan Girard", email = "stan@quivr.app" }
]
dependencies = [
    "quivr-core @ file:///${PROJECT_ROOT}/../../core",
    "chainlit>=1.2.0",
    "openai>=1.54.5",
]
readme = "README.md"
requires-python = ">= 3.11"

[tool.rye]
managed = true
virtual = true
dev-dependencies = []
