# Using a slim version for a smaller base image
FROM python:3.11.6-slim-bullseye

# Install GEOS library, Rust, and other dependencies, then clean up
RUN apt-get clean && apt-get update && apt-get install -y \
    curl \
    build-essential \
    libgeos-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
# Set the working directory
WORKDIR /code

RUN curl -sSL https://install.python-poetry.org | python3 - && \
    cd /usr/local/bin && \
    ln -s /root/.local/bin/poetry && \
    poetry config virtualenvs.create false

# Add Poetry to PATH
ENV PATH="/root/.local/bin:$PATH"

# Copy the current directory contents into the container at /app
COPY ./pyproject.toml ./poetry.lock* /code/

RUN python3 -m pip install nltk && python3 -c "import nltk; nltk.download('punkt')" \
    && python3 -c "import nltk; nltk.download('averaged_perceptron_tagger')"

# Install project dependencies
RUN poetry install  --with test

ENV PYTHONPATH=/code
