import os

from fpdf import FPDF
from pydantic import BaseModel


class PDFModel(BaseModel):
    title: str
    content: str


class PDFGenerator(FPDF):
    def __init__(self, pdf_model: PDFModel, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.pdf_model = pdf_model
        self.add_font(
            "DejaVu",
            "",
            os.path.join(os.path.dirname(__file__), "font/DejaVuSansCondensed.ttf"),
        )
        self.add_font(
            "DejaVu",
            "B",
            os.path.join(
                os.path.dirname(__file__), "font/DejaVuSansCondensed-Bold.ttf"
            ),
        )
        self.add_font(
            "DejaVu",
            "I",
            os.path.join(
                os.path.dirname(__file__), "font/DejaVuSansCondensed-Oblique.ttf"
            ),
        )

    def header(self):
        # Logo
        logo_path = os.path.join(os.path.dirname(__file__), "logo.png")
        self.image(logo_path, 10, 10, 20)  # Adjust size as needed

        # Move cursor to right of image
        self.set_xy(20, 15)

        # Title
        self.set_font("DejaVu", "B", 12)
        self.multi_cell(0, 10, self.pdf_model.title, align="C")
        self.ln(5)  # Padding after title

    def footer(self):
        self.set_y(-15)

        self.set_font("DejaVu", "I", 8)
        self.set_text_color(169, 169, 169)
        self.cell(80, 10, "Generated by Quivr", 0, 0, "C")
        self.set_font("DejaVu", "U", 8)
        self.set_text_color(0, 0, 255)
        self.cell(30, 10, "quivr.app", 0, 0, "C", link="https://www.quivr.com")

    def chapter_body(self):
        self.set_font("DejaVu", "", 12)
        content_lines = self.pdf_model.content.split("\n")
        for line in content_lines:
            if line.startswith("# "):
                self.ln()  # Add line break before header
                self.set_font("DejaVu", "B", 16)
                self.multi_cell(0, 10, line[2:], markdown=False)
            elif line.startswith("## "):
                self.ln()  # Add line break before header
                self.set_font("DejaVu", "B", 14)
                self.multi_cell(0, 10, line[3:], markdown=False)
            elif line.startswith("### "):
                self.ln()  # Add line break before header
                self.set_font("DejaVu", "B", 12)
                self.multi_cell(0, 10, line[4:], markdown=False)
            else:
                self.set_font("DejaVu", "", 12)
                self.multi_cell(0, 10, line, markdown=True)
            self.ln()

    def print_pdf(self):
        self.add_page()
        self.chapter_body()


if __name__ == "__main__":
    pdf_model = PDFModel(
        title="Summary of Legal Services Rendered by Orrick",
        content="""
# Main Header
## Sub Header
### Sub Sub Header
**Summary:** 
This is a **summary** of the legal services rendered. This is a summary of the legal services rendered. This is a summary of the legal services rendered. This is a summary of the legal services rendered. This is a summary of the legal services rendered.
Hello world
""",
    )
    pdf = PDFGenerator(pdf_model)
    pdf.print_pdf()
    pdf.output("simple.pdf")
