create table "public"."integrations_user" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "brain_id" uuid,
    "integration_id" uuid,
    "settings" jsonb,
    "credentials" jsonb
);


alter table "public"."integrations_user" enable row level security;

alter table "public"."integrations" add column "connection_settings" jsonb;

alter table "public"."integrations" alter column "id" set default gen_random_uuid();

alter table "public"."integrations" alter column "id" drop identity;

alter table "public"."integrations" alter column "id" set data type uuid using "id"::uuid;

CREATE UNIQUE INDEX integrations_user_pkey ON public.integrations_user USING btree (id);

alter table "public"."integrations_user" add constraint "integrations_user_pkey" PRIMARY KEY using index "integrations_user_pkey";

alter table "public"."integrations_user" add constraint "integrations_user_brain_id_fkey" FOREIGN KEY (brain_id) REFERENCES brains(brain_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."integrations_user" validate constraint "integrations_user_brain_id_fkey";

alter table "public"."integrations_user" add constraint "integrations_user_integration_id_fkey" FOREIGN KEY (integration_id) REFERENCES integrations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."integrations_user" validate constraint "integrations_user_integration_id_fkey";

alter table "public"."integrations_user" add constraint "integrations_user_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."integrations_user" validate constraint "integrations_user_user_id_fkey";

grant delete on table "public"."integrations_user" to "anon";

grant insert on table "public"."integrations_user" to "anon";

grant references on table "public"."integrations_user" to "anon";

grant select on table "public"."integrations_user" to "anon";

grant trigger on table "public"."integrations_user" to "anon";

grant truncate on table "public"."integrations_user" to "anon";

grant update on table "public"."integrations_user" to "anon";

grant delete on table "public"."integrations_user" to "authenticated";

grant insert on table "public"."integrations_user" to "authenticated";

grant references on table "public"."integrations_user" to "authenticated";

grant select on table "public"."integrations_user" to "authenticated";

grant trigger on table "public"."integrations_user" to "authenticated";

grant truncate on table "public"."integrations_user" to "authenticated";

grant update on table "public"."integrations_user" to "authenticated";

grant delete on table "public"."integrations_user" to "service_role";

grant insert on table "public"."integrations_user" to "service_role";

grant references on table "public"."integrations_user" to "service_role";

grant select on table "public"."integrations_user" to "service_role";

grant trigger on table "public"."integrations_user" to "service_role";

grant truncate on table "public"."integrations_user" to "service_role";

grant update on table "public"."integrations_user" to "service_role";


